# This file was generated by GoReleaser. DO NOT EDIT.
cask "tetherd" do
  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}"]
  end

  version "0.4.1-SNAPSHOT-cee83df"

  on_macos do
    on_arm do
      sha256 "c6f365e5ff92cd7d9ecd8db0674e89d483d459806a24f4d65101057adf1b7336"
      url "https://github.com/kyosu-1/tetherd/releases/download/v0.4.1/tetherd_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e25278d22176bdfae3e608d3229c774fc991613a4e5a05519443aa055bbe1040"
      url "https://github.com/kyosu-1/tetherd/releases/download/v0.4.1/tetherd_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "tetherd"
  desc "mirrord-like local development environment for ECS Fargate"
  homepage "https://github.com/kyosu-1/tetherd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tetherd"
  binary "tetherd-helper"
  binary "tetherd-exec"

  uninstall launchctl: [
      "dev.tetherd.helper",
    ],
    delete: [
      "/Library/LaunchDaemons/dev.tetherd.helper.plist",
      "/usr/local/libexec/tetherd",
    ]

  # No zap stanza required

  caveats <<~EOS
    tetherd needs a root helper for pf, /etc/resolver and the tetherd group:

      sudo tetherd-helper install

    Then run `tetherd doctor`. It checks everything else this needs,
    including the SSM session-manager-plugin, which is not installed as a
    dependency because AWS's own installer puts it somewhere Homebrew
    cannot see.

    Run that again after every upgrade - it reinstalls both binaries into a
    root-owned directory and restarts the daemon.
  EOS
end
